Wakatime improvement
* Add checks for md5 and aespipe installation before trying to decrypt
  the wakatime file
* Now conditionally loads the wakatime plugin based on whether the
  decyprted wakatime configuration is available - else output message
* Remove rust plugin from zshrc - doesn't seem to work on fedora
* Add updated omnipkg plugin that now supports fedora
* Add packages for nvidia drivers for installation on fedora

diff --git a/vim/decrypt-wakatime b/vim/decrypt-wakatime
--- a/vim/decrypt-wakatime
+++ b/vim/decrypt-wakatime
@@ -19,6 +19,16 @@ function destroy_fds {
     exec 4>&-
 }
 
+if hash ${MD5} &> /dev/null
+then
+    echo "${MD5} not found"
+    exit 1
+else if hash aespipe &> /dev/null
+then
+    echo "aespipe not found"
+    exit 1
+fi
+
 TRIES=0
 MAX_TRIES=3
 
